
export enum UserRole {
  SUPER_ADMIN = "super_admin",
  OWNER = "owner",
  ADMIN = "admin",
  MANAGER = "manager",
  CASHIER = "cashier",
  KITCHEN = "kitchen",
}

export const RolePermissions = {
  [UserRole.SUPER_ADMIN]: {
    canManageBusiness: true,
    canManageUsers: true,
    canManageInventory: true,
    canViewReports: true,
    canManageSettings: true,
    canProcessSales: true,
    canManageShifts: true,
    canApproveDiscounts: true,
    isKDS: true,
    isSuperAdmin: true,
  },
  [UserRole.OWNER]: {
    canManageBusiness: true,
    canManageUsers: true,
    canManageInventory: true,
    canViewReports: true,
    canManageSettings: true,
    canProcessSales: true,
    canManageShifts: true,
    canApproveDiscounts: true,
    isKDS: true,
    isSuperAdmin: false,
  },
  [UserRole.ADMIN]: {
    canManageBusiness: true,
    canManageUsers: true,
    canManageInventory: true,
    canViewReports: true,
    canManageSettings: true,
    canProcessSales: true,
    canManageShifts: true,
    canApproveDiscounts: true,
    isKDS: true,
    isSuperAdmin: false,
  },
  [UserRole.MANAGER]: {
    canManageBusiness: false,
    canManageUsers: false,
    canManageInventory: true,
    canViewReports: true,
    canManageSettings: false,
    canProcessSales: true,
    canManageShifts: true,
    canApproveDiscounts: true,
    isKDS: true,
    isSuperAdmin: false,
  },
  [UserRole.CASHIER]: {
    canManageBusiness: false,
    canManageUsers: false,
    canManageInventory: false,
    canViewReports: true,
    canManageSettings: true,
    canProcessSales: true,
    canManageShifts: false,
    canApproveDiscounts: false,
    isKDS: false,
    isSuperAdmin: false,
  },
  [UserRole.KITCHEN]: {
    canManageBusiness: false,
    canManageUsers: false,
    canManageInventory: false,
    canViewReports: false,
    canManageSettings: false,
    canProcessSales: false,
    canManageShifts: false,
    canApproveDiscounts: false,
    isKDS: true,
    isSuperAdmin: false,
  },
}
